<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContactSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('contacts')->insert([
            [
                'id' => 1,
                'street' => 'Prinses Irenestraat',
                'house_number' => '12',
                'addition' => 'A',
                'postal_code' => '5271TH',
                'city' => 'Maaskantje',
                'email' => 'j.van.zevenhuizen@gmail.com',
                'mobile' => '+31 623456123',
                'is_active' => true,
                'note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'street' => 'Gibraltarstraat',
                'house_number' => '234',
                'addition' => null,
                'postal_code' => '5271TJ',
                'city' => 'Maaskantje',
                'email' => 'a.bergkamp@hotmail.com',
                'mobile' => '+31 623456123',
                'is_active' => true,
                'note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'street' => 'Der Kinderstraat',
                'house_number' => '456',
                'addition' => 'Bis',
                'postal_code' => '5271TH',
                'city' => 'Maaskantje',
                'email' => 's.van.de.heuvel@gmail.com',
                'mobile' => '+31 623456123',
                'is_active' => true,
                'note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'street' => 'Nachtegaalstraat',
                'house_number' => '233',
                'addition' => 'A',
                'postal_code' => '5271TJ',
                'city' => 'Maaskantje',
                'email' => 'e.scherder@gmail.com',
                'mobile' => '+31 623456123',
                'is_active' => true,
                'note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'street' => 'Bertram Russellstraat',
                'house_number' => '45',
                'addition' => null,
                'postal_code' => '5271TH',
                'city' => 'Maaskantje',
                'email' => 'f.de.jong@hotmail.com',
                'mobile' => '+31 623456123',
                'is_active' => true,
                'note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'street' => 'Leonardo Da VinciHof',
                'house_number' => '34',
                'addition' => null,
                'postal_code' => '5271ZE',
                'city' => 'Maaskantje',
                'email' => 'h.van.der.berg@gmail.com',
                'mobile' => '+31 623456123',
                'is_active' => true,
                'note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'street' => 'Siegfried Knutsenlaan',
                'house_number' => '234',
                'addition' => null,
                'postal_code' => '5271ZE',
                'city' => 'Maaskantje',
                'email' => 'r.ter.weijden@ah.nl',
                'mobile' => '+31 623456123',
                'is_active' => true,
                'note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'street' => 'Theo de Bokstraat',
                'house_number' => '256',
                'addition' => null,
                'postal_code' => '5271ZH',
                'city' => 'Maaskantje',
                'email' => 'l.pastoor@gmail.com',
                'mobile' => '+31 623456123',
                'is_active' => true,
                'note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'street' => 'Meester van Leerhof',
                'house_number' => '2',
                'addition' => 'A',
                'postal_code' => '5271ZH',
                'city' => 'Maaskantje',
                'email' => 'm.yazidi@gemeenteutrecht.nl',
                'mobile' => '+31 623456123',
                'is_active' => true,
                'note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'street' => 'Van Wemelenplantsoen',
                'house_number' => '300',
                'addition' => null,
                'postal_code' => '5271TH',
                'city' => 'Maaskantje',
                'email' => 'b.van.driel@gmail.com',
                'mobile' => '+31 623456123',
                'is_active' => true,
                'note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'street' => 'Terlingenhof',
                'house_number' => '20',
                'addition' => null,
                'postal_code' => '5271TH',
                'city' => 'Maaskantje',
                'email' => 'j.pastorius@gmail.com',
                'mobile' => '+31 623456356',
                'is_active' => true,
                'note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'street' => 'Veldhoen',
                'house_number' => '31',
                'addition' => null,
                'postal_code' => '5271ZE',
                'city' => 'Maaskantje',
                'email' => 's.dollaard@gmail.com',
                'mobile' => '+31 623452314',
                'is_active' => true,
                'note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'street' => 'ScheringaDreef',
                'house_number' => '37',
                'addition' => null,
                'postal_code' => '5271ZE',
                'city' => 'Vught',
                'email' => 'j.blokker@gemeentevught.nl',
                'mobile' => '+31 623452314',
                'is_active' => true,
                'note' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
