<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            ['id'=>1,  'category_id'=>1, 'name'=>'Aardappel',      'allergy_type'=>null,      'barcode'=>'8719587321239', 'expiration_date'=>'2025-07-12', 'description'=>'Kruimige aardappel',         'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>2,  'category_id'=>1, 'name'=>'Aardappel',      'allergy_type'=>null,      'barcode'=>'8719587321239', 'expiration_date'=>'2025-07-26', 'description'=>'Kruimige aardappel',         'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>3,  'category_id'=>1, 'name'=>'Ui',             'allergy_type'=>null,      'barcode'=>'8719437321335', 'expiration_date'=>'2025-09-02', 'description'=>'Gele ui',                    'status'=>'NietOpVoorraad',         'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>4,  'category_id'=>1, 'name'=>'Appel',          'allergy_type'=>null,      'barcode'=>'8719486321332', 'expiration_date'=>'2025-08-16', 'description'=>'Granny Smith',               'status'=>'NietLeverbaar',          'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>5,  'category_id'=>1, 'name'=>'Appel',          'allergy_type'=>null,      'barcode'=>'8719486321332', 'expiration_date'=>'2025-09-23', 'description'=>'Granny Smith',               'status'=>'NietLeverbaar',          'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>6,  'category_id'=>1, 'name'=>'Banaan',         'allergy_type'=>'Banaan',  'barcode'=>'8719484321336', 'expiration_date'=>'2025-07-12', 'description'=>'Biologische Banaan',         'status'=>'OverHoudbaarheidsDatum', 'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>7,  'category_id'=>1, 'name'=>'Banaan',         'allergy_type'=>'Banaan',  'barcode'=>'8719484321336', 'expiration_date'=>'2025-07-19', 'description'=>'Biologische Banaan',         'status'=>'OverHoudbaarheidsDatum', 'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>8,  'category_id'=>2, 'name'=>'Kaas',           'allergy_type'=>'Lactose', 'barcode'=>'8719487421338', 'expiration_date'=>'2025-09-19', 'description'=>'Jonge Kaas',                 'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>9,  'category_id'=>2, 'name'=>'Rosbief',        'allergy_type'=>null,      'barcode'=>'8719487421331', 'expiration_date'=>'2025-07-23', 'description'=>'Rundvlees',                  'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>10, 'category_id'=>3, 'name'=>'Melk',           'allergy_type'=>'Lactose', 'barcode'=>'8719447321332', 'expiration_date'=>'2025-07-23', 'description'=>'Halfvolle melk',             'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>11, 'category_id'=>3, 'name'=>'Margarine',      'allergy_type'=>null,      'barcode'=>'8719486321336', 'expiration_date'=>'2025-08-02', 'description'=>'Plantaardige boter',         'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>12, 'category_id'=>3, 'name'=>'Ei',             'allergy_type'=>'Eier',    'barcode'=>'8719487421334', 'expiration_date'=>'2025-08-04', 'description'=>'Scharrelei',                 'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>13, 'category_id'=>4, 'name'=>'Brood',          'allergy_type'=>'Gluten',  'barcode'=>'8719487721337', 'expiration_date'=>'2025-07-07', 'description'=>'Volkoren brood',              'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>14, 'category_id'=>4, 'name'=>'Gevulde Koek',   'allergy_type'=>'Amandel', 'barcode'=>'8719488332133', 'expiration_date'=>'2025-09-24', 'description'=>'Banketbakkers kwaliteit',     'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>15, 'category_id'=>5, 'name'=>'Fristi',         'allergy_type'=>'Lactose', 'barcode'=>'8719487121331', 'expiration_date'=>'2025-10-28', 'description'=>'Frisdrank',                   'status'=>'NietOpVoorraad',         'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>16, 'category_id'=>5, 'name'=>'Appelsap',       'allergy_type'=>null,      'barcode'=>'8719487521335', 'expiration_date'=>'2025-10-19', 'description'=>'100% vruchtensap',            'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>17, 'category_id'=>5, 'name'=>'Koffie',         'allergy_type'=>'Caffeine','barcode'=>'8719487831328', 'expiration_date'=>'2025-09-23', 'description'=>'Arabica koffie',              'status'=>'OverHoudbaarheidsDatum', 'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>18, 'category_id'=>5, 'name'=>'Thee',           'allergy_type'=>'Theïne',  'barcode'=>'8719487329339', 'expiration_date'=>'2025-09-02', 'description'=>'Ceylon thee',                 'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>19, 'category_id'=>6, 'name'=>'Pasta',          'allergy_type'=>'Gluten',  'barcode'=>'8719487321334', 'expiration_date'=>'2025-12-16', 'description'=>'Macaroni',                    'status'=>'NietLeverbaar',          'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>20, 'category_id'=>6, 'name'=>'Rijst',          'allergy_type'=>null,      'barcode'=>'8719487331332', 'expiration_date'=>'2025-12-25', 'description'=>'Basmati Rijst',               'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>21, 'category_id'=>6, 'name'=>'Knorr Nasi Mix', 'allergy_type'=>null,      'barcode'=>'8719487531535', 'expiration_date'=>'2025-12-13', 'description'=>'Nasi kruiden',                'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>22, 'category_id'=>7, 'name'=>'Tomatensoep',    'allergy_type'=>null,      'barcode'=>'8719487731337', 'expiration_date'=>'2025-12-23', 'description'=>'Romige tomatensoep',          'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>23, 'category_id'=>7, 'name'=>'Tomatensaus',    'allergy_type'=>null,      'barcode'=>'8719487731337', 'expiration_date'=>'2025-12-23', 'description'=>'Pizza saus',                   'status'=>'NietOpVoorraad',         'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>24, 'category_id'=>7, 'name'=>'Peterselie',     'allergy_type'=>null,      'barcode'=>'8719487321636', 'expiration_date'=>'2025-07-31', 'description'=>'Verse kruidenpot',             'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>25, 'category_id'=>8, 'name'=>'Olie',           'allergy_type'=>null,      'barcode'=>'8719487327337', 'expiration_date'=>'2025-12-27', 'description'=>'Olijfolie',                    'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>26, 'category_id'=>8, 'name'=>'Mars',           'allergy_type'=>null,      'barcode'=>'8719487311331', 'expiration_date'=>'2025-12-11', 'description'=>'Snoep',                        'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>27, 'category_id'=>8, 'name'=>'Biscuit',        'allergy_type'=>null,      'barcode'=>'8719487311331', 'expiration_date'=>'2025-08-07', 'description'=>'San Francisco biscuit',        'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>28, 'category_id'=>8, 'name'=>'Paprika Chips',  'allergy_type'=>null,      'barcode'=>'87194873218398','expiration_date'=>'2025-12-22', 'description'=>'Ribbelchips paprika',           'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
            ['id'=>29, 'category_id'=>8, 'name'=>'Chocolade reep', 'allergy_type'=>'Cacoa',   'barcode'=>'8719487321533', 'expiration_date'=>'2025-11-21', 'description'=>'Tony Chocolonely',             'status'=>'OpVoorraad',            'is_active'=>true, 'note'=>null, 'created_at'=>now(), 'updated_at'=>now()],
        ]);
    }
}
